### PR TITLE
added avataaars

### PR DESCRIPTION
**Pull request by simonfranz**
Added the images from https://avataaars.com/ as single parts as "set5" and updated the docs.

### CODE REVIEW

**Comment by ladaposamuel** [comment]
Lovely

**Comment by ladaposamuel** [comment]
waiting for this

**Comment by simonfranz** [comment]
me too :D

**Comment by simonfranz** [comment]
@e1ven is there anything I can do to speed up the merge?

**Comment by e1ven** [comment]
This looks really great, I love that you spent the time to add a demo and quotes! Well done.
Sorry for the delay in merging this.

**Comment by simonfranz** [comment]
Are there any plans to publish it on www.robohash.org?

**Comment by e1ven** [comment]
If you try the Params it should work. It's caching the homepage.

**Comment by simonfranz** [comment]
Awesome!! Thank you!
Thank you

**Pull request merged**
