### PR TITLE
Project improvements!

### PR DESCRIPTION
**Pull request by singingwolfboy**
This seems like a nifty project, and I wanted to help make a few improvements. This pull request does the following:

* Adds dependency information to the `setup.py`, including the optional `tornado` dependency for the web frontend
* Adds package data, license, and classifiers to `setup.py`
* Reformats README to use Markdown
* Adds installation and usage information to the README

### CODE REVIEW

**Comment by e1ven** [comment]
Thanks!

**Comment by singingwolfboy** [comment]
You're very welcome! Any chance you could make a new release and put it on PyPI, as well?

**Comment by MikeDX** [comment]
I'm surprised this was merged as setup.py references readme.txt which now no longer exists.

Also setup.py has been reformatted for no real reason (spaces before and after = signs)

**Comment by singingwolfboy** [comment]
@MikeDX Thanks for pointing that out! Everybody makes mistakes, and I've created #16 to fix that.

I reformatted `setup.py` to bring it in line with standard [PEP 8](https://www.python.org/dev/peps/pep-0008/) formatting guidelines.

**Pull request merged**
