### PR TITLE
Load description from README.md

### PR DESCRIPTION
**Pull request by singingwolfboy**
Forgot something from #15!

### CODE REVIEW

**Comment by MikeDX** [comment]
Does this cause problems rendering since markdown isn't as plain formatted as plain text? (I mean literally, since it has leading # etc)

I can't test since I'm nowhere near a computer but I'd be interested to see the output of setup.py and how it looks rendered in a terminal

**Comment by singingwolfboy** [comment]
@MikeDX: rendering what, where?

**Comment by MikeDX** [comment]
The contents of readme.md is now the long_description tag.

I assume this gets displayed/rendered somewhere... (Eventually)

**Comment by e1ven** [comment]
It looks like the preferred formatting is to use Restructuredtext.
I've made a new commit using that formatting.

**Pull request closed without merging**
